version: "3.2"

services:
  traefik:
    image: traefik:1.7-alpine
    container_name: traefik
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    ports:
      - 80:80
      - 443:443
    networks:
      - web

  db:
    image: mysql:5.7
    container_name: pmbdb
    restart: unless-stopped
    volumes:
      - ./.data/db:/var/lib/mysql
      - ./php7/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${CONTAINER_TIMEZONE}
    networks:
      - default

  php:
    build:
      context: php7
      args:
        PMB_VERSION: ${PMB_VERSION}
    container_name: pmbphp
    restart: unless-stopped
    volumes:
      - ../doc_num:/var/www/pmb/doc_num
      - ../docscdi:/var/www/pmb/docscdi
#      - ../docscdi_zen:/var/www/pmb/docscdi_zen
      - ../.img_cache:/var/www/pmb/img_cache
    environment:
      TZ: ${CONTAINER_TIMEZONE}
    networks:
      - web
      - default
    labels:
      - "traefik.frontend.rule=Host:${TRAEFIK_HOST}"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.port=80"

networks:
  web:
    external: true
  default:
